data_path:
  - Demand.csv
  - ETTh1.csv
  - ETTh2.csv

target: 
  - target

seq_len:
  - 18
  - 24
  - 30

pred_len:
  - 18

emb_len:
  - 8

d_model:
  - 8
  - 16
  - 32
  - 64

batch_size: 
  - 32

n_layers:
  - 1
  - 2
  - 3
  - 4
  - 5

patience:
  - 10

learning_rate: 
  - 0.003

train_epochs: 
  - 100

dropout: 
  - 0.3

reduce_data:
  - 1

iters: 
  - 3

use_gpu: 
  - true

gpu: 
  - 0

num_workers: 
  - 8

step: 
  - 1